# Utiliza la imagen oficial de PostgreSQL 15.6 como base
FROM postgres:15.6

# Variables de entorno para configurar el usuario y la contraseña
ENV POSTGRES_USER=ensamblaTec
ENV POSTGRES_PASSWORD=password

# Variable para configurar el nombre de la base de datos
ENV POSTGRES_DB=security

# Puerto por defecto de PostgreSQL
EXPOSE 5432
